{% extends "projects/lkft-android/cts.yaml" %}

{% set test_timeout = 600 %}
{% set test_name = "cts-security" %}
{% set cts_test_plan = "cts" %}

{% block cts_test_params %}cts
                -m CtsSecurityTestCases
                -m CtsSecurityTestCases[instant]
                -m CtsAppSecurityHostTestCases
                --disable-reboot
{% endblock cts_test_params %}
